LIBS-1222 - updated dependencies/image (compatibility to apple-chips)
springboot-testcontainer/springboot-testcontainer-rabbitmq pull request #22
Opened 2023-03-28 12:53 UTC by Schubi1981

2023-03-29 15:51 UTC, julian-eggers approved these changes, later dismissed

2023-03-29 18:51 UTC, fegbers requested changes

2023-03-29 18:51 UTC, fegbers commented on pom.xml
> +      <scope>provided</scope>
Weshalb die Änderung im Scope? Sollte nicht notwendig sein? Ansonsten müsste die Dependency zu dem Other-Block

2023-03-30 11:14 UTC, fegbers approved these changes

2023-03-30 11:21 UTC, julian-eggers approved these changes

2023-03-30 11:21 UTC, merged